# Generated by Django 5.2 on 2025-04-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_hr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hr",
            name="company_nip",
            field=models.CharField(max_length=10),
        ),
    ]
