# Generated by Django 5.2 on 2025-04-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_hr_company_nip"),
    ]

    operations = [
        migrations.AddField(
            model_name="hr",
            name="country",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
