# Generated by Django 5.2 on 2025-06-07 22:36

import django.db.models.deletion
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_hr_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="hr_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="trial_used_hr",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "admin"),
                    ("User", "user"),
                    ("Hr", "hr"),
                    ("Premium", "premium"),
                ],
                default="User",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Premium",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(default=users.models.default_premium_expiry),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
