# Generated by Django 5.2 on 2025-06-07 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_hr_expires_at_customuser_trial_used_hr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="premium",
            name="expires_at",
        ),
    ]
