# Generated by Django 5.2 on 2025-06-11 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_customuser_role_customuser_hr_role_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
