# Generated by Django 5.2 on 2025-06-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_customuser_managers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hr",
            old_name="user",
            new_name="user_id",
        ),
        migrations.RenameField(
            model_name="premium",
            old_name="user",
            new_name="user_id",
        ),
    ]
