# Generated by Django 5.2 on 2025-06-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvinfo",
            name="avatar",
            field=models.ImageField(null=True, upload_to="test/"),
        ),
    ]
