# Generated by Django 5.2 on 2025-06-04 22:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0002_cvinfo_avatar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvinfo",
            name="avatar",
            field=models.ImageField(
                null=True,
                upload_to="<function CustomUser.get_id at 0x0000016BF00B05E0>/",
            ),
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("telephone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("city", models.CharField(max_length=255)),
                (
                    "cv_info_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactLinks",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("link", models.CharField(max_length=255)),
                (
                    "contact_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cv.contact"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(null=True)),
                (
                    "cv_info_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cv.cvinfo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Duties",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField(max_length=500)),
                (
                    "experience_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cv.experience"
                    ),
                ),
            ],
        ),
    ]
