# Generated by Django 5.2 on 2025-06-05 21:18

import cv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0004_alter_contactlinks_link_alter_contactlinks_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvinfo",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=cv.models.user_avatar_upload_path
            ),
        ),
    ]
