# Generated by Django 5.2 on 2025-06-05 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0005_alter_cvinfo_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cvinfo",
            name="city",
        ),
        migrations.RemoveField(
            model_name="cvinfo",
            name="country",
        ),
        migrations.RemoveField(
            model_name="cvinfo",
            name="telephone",
        ),
    ]
