# Generated by Django 5.2 on 2025-06-05 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0006_remove_cvinfo_city_remove_cvinfo_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cvinfo",
            name="email",
        ),
    ]
