# Generated by Django 5.2 on 2025-06-05 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0007_remove_cvinfo_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="cv_info_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="cv.cvinfo"
            ),
        ),
    ]
