# Generated by Django 5.2 on 2025-06-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0008_alter_contact_cv_info_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
