# Generated by Django 5.2 on 2025-06-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0009_alter_education_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
