# Generated by Django 5.2 on 2025-06-09 08:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0011_cvinfo_thumbnail_alter_cvinfo_userid"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Intrests",
            new_name="Interests",
        ),
        migrations.AddField(
            model_name="experience",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "cv_info_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cv.cvinfo"
                    ),
                ),
            ],
        ),
    ]
