# Generated by Django 5.2 on 2025-06-10 22:41

import cv.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0013_projects_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cvinfo",
            name="userId",
        ),
        migrations.RemoveField(
            model_name="education",
            name="cv_info_id",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="cv_info_id",
        ),
        migrations.RemoveField(
            model_name="hardskills",
            name="cv_info_id",
        ),
        migrations.RemoveField(
            model_name="interests",
            name="cv_info_id",
        ),
        migrations.RemoveField(
            model_name="languages",
            name="cv_info_id",
        ),
        migrations.RemoveField(
            model_name="projects",
            name="cv_info_id",
        ),
        migrations.RemoveField(
            model_name="softskills",
            name="cv_info_id",
        ),
        migrations.AlterField(
            model_name="cvinfo",
            name="avatar",
            field=models.ImageField(upload_to=cv.models.user_avatar_upload_path),
        ),
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cvinfo",
            name="cv_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cv.cv",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="cv_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cv.cv",
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="cv_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cv.cv",
            ),
        ),
        migrations.AddField(
            model_name="hardskills",
            name="cv_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cv.cv",
            ),
        ),
        migrations.AddField(
            model_name="interests",
            name="cv_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cv.cv",
            ),
        ),
        migrations.AddField(
            model_name="languages",
            name="cv_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cv.cv",
            ),
        ),
        migrations.AddField(
            model_name="projects",
            name="cv_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cv.cv",
            ),
        ),
        migrations.AddField(
            model_name="softskills",
            name="cv_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cv.cv",
            ),
        ),
    ]
