# Generated by Django 5.2 on 2025-06-10 22:42

import cv.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0014_remove_cvinfo_userid_remove_education_cv_info_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvinfo",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=cv.models.user_avatar_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="cvinfo",
            name="cv_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cv.cv"
            ),
        ),
    ]
