# Generated by Django 5.2 on 2025-06-10 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0015_alter_cvinfo_avatar_alter_cvinfo_cv_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvinfo",
            name="cv_id",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to="cv.cv"
            ),
        ),
    ]
