# Generated by Django 5.2 on 2025-06-11 20:31

import cv.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0017_alter_cvinfo_cv_id_alter_education_cv_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cvinfo",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="cv",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to=cv.models.user_avatar_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="cv_id",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to="cv.cv"
            ),
        ),
        migrations.AlterField(
            model_name="hardskills",
            name="cv_id",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to="cv.cv"
            ),
        ),
        migrations.AlterField(
            model_name="interests",
            name="cv_id",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to="cv.cv"
            ),
        ),
        migrations.AlterField(
            model_name="languages",
            name="cv_id",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to="cv.cv"
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="cv_id",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to="cv.cv"
            ),
        ),
        migrations.AlterField(
            model_name="softskills",
            name="cv_id",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to="cv.cv"
            ),
        ),
    ]
