# Generated by Django 5.2 on 2025-06-11 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0018_remove_cvinfo_thumbnail_cv_thumbnail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvinfo",
            name="cv_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="cv.cv"
            ),
        ),
    ]
