# Generated by Django 5.2 on 2025-06-11 21:07

import cv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0019_alter_cvinfo_cv_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="thumbnail",
            field=models.ImageField(
                blank=True, upload_to=cv.models.user_avatar_upload_path
            ),
        ),
    ]
