# Generated by Django 5.2 on 2025-06-11 21:15

import cv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0022_alter_cv_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvinfo",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to=cv.models.user_avatar_upload_path
            ),
        ),
    ]
