# Generated by Django 5.2 on 2025-06-24 18:24

import cv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0023_alter_cvinfo_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvinfo",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=cv.models.user_avatar_upload_path
            ),
        ),
    ]
