# Generated by Django 5.2 on 2025-06-24 18:28

import cv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0024_alter_cvinfo_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="thumbnail",
            field=models.FileField(
                blank=True, upload_to=cv.models.user_avatar_upload_path
            ),
        ),
    ]
