# Generated by Django 5.2 on 2025-06-27 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0026_alter_cv_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cvinfo",
            name="created_at",
        ),
    ]
